language: ruby
os: osx

rvm:
 - "2.2.3"

before_script:
 #Update brew. Dont `brew upgrade` -> There are a bunch of deps that we don't use
 - brew update
 #Install Cask
 - brew install caskroom/cask/brew-cask

 #Foor good measure...
 - brew update

script:
 - ruby lib/test-all.rb